### ISSUE TITLE
GITHUB_OUTPUT variable not defined by default

### ISSUE THREAD

**Issue by acottre** [actions/hello-world-docker-action#14]
Hi

Running as per the documentation, with just 
```    
steps:
    - uses: actions/hello-world-docker-action@main
      with:
        who-to-greet: 'acottre'
```

Fails the run with
```
Hello acottre
/entrypoint.sh: line 5: can't create : nonexistent directory
##[debug]Docker Action run completed with exit code 1
```

As there is no default for this variable in entrypoint.sh

Can I recommend either updating the documentation to include this variable, or having a default set?

Running on a self hosted action runner on github enterprise server 3.7.2
