### ISSUE TITLE
HowTo pass context to Docker actions

### ISSUE THREAD

**Issue by fogfish** [actions/hello-world-docker-action#5]
Some actions uses these construct for input variables

```
input:
  title:
    description: 'pull request title'
    required: true
    default: ${{ github.event.pull_request.title }}
```

but it fails with

```
##[error](Line: 10, Col: 14): Unrecognized named-value: 'github'. Located at position 1 within expression: 
```

Is it possible to use context with docker based actions or is it a unique feature for JavaScript actions only?

**Comment by fogfish** [comment]
I've not found anything else than parsing an event with `jq`. 

```
TITLE=$(jq -r '.pull_request.title' < ${GITHUB_EVENT_PATH})
```

**Comment by dakale** [comment]
Hey 👋 Sorry for the late reply... hopefully this is still useful

I was able to reproduce this. I took the sample from this repo and changed the action yaml to:

```yaml
# File: action.yaml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: ${{ github.actor }}
outputs:
  time: 
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
```

which access the `github` context (where your error was). The difference that reproduced the error is `input` vs `inputs`. Basically we have "well-known" locations where certains contexts are allowed (`inputs` is one that allows `github`).

Hope that helps!
